name: Manage Certificates
run-name: Manage Certificates (${{ github.ref_name }})
on:
  workflow_dispatch:
    inputs:
      expiration_threshold:
        description: "Days before expiration to check certificates"
        required: false
        default: "30"

jobs:
  manage_certificates:
    runs-on: macos-latest
    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set Up Ruby and Fastlane
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Specify the Ruby version needed for Fastlane

      - name: Install Fastlane
        run: gem install fastlane

      # Step 3: Run the Manage Certificates Lane
      - name: Manage Certificates
        run: fastlane ios manage_certs
        env:
          TEAMID: ${{ secrets.TEAMID }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GH_PAT: ${{ secrets.GH_PAT }}
          CERT_EXPIRATION_THRESHOLD: ${{ github.event.inputs.expiration_threshold }}

      # Step 4: Post Workflow Summary (Optional)
      - name: Notify Success
        if: success()
        run: echo "Certificate management completed successfully."

      - name: Notify Failure
        if: failure()
        run: echo "Certificate management failed. Please check the logs."
